<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Noorestan.MazinoorImport\Noorestan.MazinoorImport.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="SeedData\mazinoor\images\**\*.jpg" CopyToOutputDirectory="PreserveNewest" />
    <Content Update="SeedData\**\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
