import { ChangeDetectionStrategy, Component, computed, signal } from '@angular/core';
import { products } from '../../core/catalog-data';
import { ProductCardComponent } from '../../shared/product-card.component';

@Component({selector:'app-catalog',imports:[ProductCardComponent],changeDetection:ChangeDetectionStrategy.OnPush,template:`
<header class="page-head"><span>کاتالوگ محصولات</span><h1>روشنایی دقیق،<br>برای فضای ماندگار</h1><p>در میان محصولات مازی‌نور جست‌وجو کنید و برای انتخاب، قیمت و موجودی با نورستان گفت‌وگو کنید.</p></header>
<section class="catalog"><aside><label for="search">جست‌وجوی محصول</label><div class="search"><input id="search" type="search" [value]="query()" (input)="setQuery($event)" placeholder="نام، کد یا دسته‌بندی"><span>⌕</span></div><fieldset><legend>دسته‌بندی</legend>@for(item of categoryOptions;track item){<button type="button" [class.active]="category()===item" (click)="category.set(item)">{{item}}</button>}</fieldset><div class="help"><span>محصول مناسب را پیدا نکردید؟</span><a href="/contact">از ما بپرسید ←</a></div></aside><div><div class="result-head"><p><b>{{filtered().length}}</b> محصول</p><span>مرتب‌سازی: پیشنهادی</span></div><div class="grid">@for(product of filtered();track product.slug){<app-product-card [product]="product"/>}@empty{<div class="empty"><h2>نتیجه‌ای پیدا نشد</h2><p>عبارت جست‌وجو یا دسته‌بندی را تغییر دهید.</p><button type="button" (click)="reset()">پاک‌کردن فیلترها</button></div>}</div></div></section>
`,styles:[`.page-head{max-width:80rem;margin:auto;padding:clamp(4rem,9vw,8rem) clamp(1rem,4vw,2.5rem) 4rem;background:radial-gradient(circle at 15% 50%,rgb(139 212 255/12%),transparent 25%)}.page-head>span{color:var(--color-primary);font-size:.75rem}.page-head h1{margin:.8rem 0 1rem;font-size:clamp(3rem,7vw,6.2rem);line-height:1.05;letter-spacing:-.07em}.page-head p{max-width:40rem;color:var(--color-text-muted)}.catalog{display:grid;grid-template-columns:17rem 1fr;gap:3rem;max-width:80rem;margin:auto;padding:1rem clamp(1rem,4vw,2.5rem) var(--space-section)}aside{position:sticky;inset-block-start:7rem;align-self:start}label,legend{display:block;margin-block-end:.7rem;color:var(--color-text-muted);font-size:.75rem}.search{display:flex;border:1px solid var(--color-border);border-radius:var(--radius-md);background:var(--color-surface)}.search input{min-width:0;width:100%;padding:.8rem;border:0;outline:0;background:transparent;color:var(--color-text)}.search span{padding:.7rem;color:var(--color-primary)}fieldset{display:flex;flex-direction:column;gap:.35rem;margin:2rem 0;padding:0;border:0}fieldset button{padding:.65rem .8rem;border:0;border-inline-start:2px solid transparent;background:transparent;color:var(--color-text-muted);text-align:start}fieldset button:hover,fieldset button.active{border-color:var(--color-primary);background:rgb(139 212 255/6%);color:var(--color-text)}.help{padding:1rem;border:1px solid var(--color-border);border-radius:var(--radius-md);background:var(--color-surface);font-size:.75rem}.help span{display:block;color:var(--color-text-muted)}.help a{color:var(--color-primary);text-decoration:none}.result-head{display:flex;justify-content:space-between;align-items:center;margin-block-end:1.2rem;color:var(--color-text-muted);font-size:.75rem}.result-head b{color:var(--color-text);font-size:1rem}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1.2rem}.empty{grid-column:1/-1;padding:5rem 2rem;border:1px dashed var(--color-border);border-radius:var(--radius-lg);text-align:center}.empty p{color:var(--color-text-muted)}.empty button{padding:.7rem 1rem;border:1px solid var(--color-primary);border-radius:999px;background:transparent;color:var(--color-primary)}@media(max-width:52rem){.catalog{grid-template-columns:1fr}aside{position:static}fieldset{display:grid;grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}}`]})
export class CatalogComponent {
 protected readonly query=signal(''); protected readonly category=signal('همه محصولات'); protected readonly categoryOptions=['همه محصولات',...new Set(products.map(p=>p.category))];
 protected readonly filtered=computed(()=>{const q=this.query().trim().toLocaleLowerCase('fa');const c=this.category();return products.filter(p=>(c==='همه محصولات'||p.category===c)&&(!q||`${p.name} ${p.code} ${p.category}`.toLocaleLowerCase('fa').includes(q)));});
 protected setQuery(event:Event):void{this.query.set((event.target as HTMLInputElement).value)} protected reset():void{this.query.set('');this.category.set('همه محصولات')}
}
