import { ChangeDetectionStrategy, Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { categories, products } from '../../core/catalog-data';
import { ProductCardComponent } from '../../shared/product-card.component';

@Component({selector:'app-home',imports:[RouterLink,ProductCardComponent],changeDetection:ChangeDetectionStrategy.OnPush,template:`
<section class="hero"><div class="hero-grid"><div class="hero-copy"><span class="eyebrow"><i></i> نماینده فروش محصولات مازی‌نور</span><h1>نور، زبان<br><em>معماری</em> است.</h1><p>نورستان با شناخت فنی و نگاه معماری، شما را برای انتخاب راهکارهای روشنایی حرفه‌ای مازی‌نور همراهی می‌کند.</p><div class="actions"><a class="primary" routerLink="/products">مشاهده محصولات <span>←</span></a><a class="secondary" routerLink="/contact">گفت‌وگو با مشاور</a></div><div class="trust"><span><b>+۲۰</b> سال تجربه</span><span><b>۱۰۰٪</b> مشاوره تخصصی</span><span><b>ملی</b> پوشش پروژه</span></div></div><div class="architecture" role="img" aria-label="ترکیب انتزاعی نورپردازی معماری"><div class="light-line l1"></div><div class="light-line l2"></div><div class="light-line l3"></div><div class="arch a1"></div><div class="arch a2"></div><span>PRECISION<br>IN LIGHT</span></div></div><a class="scroll" href="#categories">کاوش کنید <i>↓</i></a></section>
<section id="categories" class="section"><div class="heading"><div><span class="eyebrow">دسته‌بندی محصولات</span><h2>راهکار روشنایی<br>برای هر فضا</h2></div><a routerLink="/products">همه محصولات ←</a></div><div class="category-grid">@for(category of categories;track category[0];let i=$index){<a routerLink="/products" class="category"><span>۰{{i+1}}</span><div class="category-light"></div><h3>{{category[0]}}</h3><p>{{category[1]}}</p><small>{{category[2]}}</small></a>}</div></section>
<section class="section featured"><div class="heading"><div><span class="eyebrow">منتخب نورستان</span><h2>محصولات شاخص</h2></div><p>انتخاب‌هایی برای پروژه‌هایی که کیفیت نور و دقت اجرا در آن‌ها تعیین‌کننده است.</p></div><div class="product-grid">@for(product of products.slice(0,3);track product.slug){<app-product-card [product]="product"/>}</div></section>
<section class="section why"><div class="why-visual"><div class="vertical-light"></div><span>NOORESTAN<br>LIGHTING</span></div><div class="why-copy"><span class="eyebrow">چرا نورستان؟</span><h2>از انتخاب محصول<br>تا روشن‌شدن فضا</h2><p>ما فقط محصول معرفی نمی‌کنیم؛ نیاز پروژه، کیفیت نور، محدودیت‌های اجرا و نتیجه نهایی را کنار هم می‌بینیم.</p><div class="reasons"><article><b>۰۱</b><h3>مشاوره فنی</h3><p>انتخاب آگاهانه بر پایه کاربرد، نور و مشخصات پروژه.</p></article><article><b>۰۲</b><h3>محصولات معتبر</h3><p>دسترسی به سبد حرفه‌ای محصولات روشنایی مازی‌نور.</p></article><article><b>۰۳</b><h3>پاسخ‌گویی مستقیم</h3><p>استعلام قیمت، موجودی و سفارش از مسیر ارتباطی روشن.</p></article></div></div></section>
<section class="section intro"><span class="eyebrow">درباره نورستان</span><blockquote>«روشنایی خوب دیده نمی‌شود؛<br>فضا را <em>دیدنی</em> می‌کند.»</blockquote><p>نورستان، همراه معماران، طراحان و کارفرمایانی است که نور را بخشی از کیفیت فضا می‌دانند.</p><a routerLink="/company">داستان نورستان ←</a></section>
<section class="contact-band"><div><span class="eyebrow">شروع یک گفت‌وگوی روشن</span><h2>برای پروژه بعدی<br>کنار شما هستیم.</h2></div><div><p>برای دریافت مشاوره، استعلام قیمت و بررسی موجودی محصولات با نورستان تماس بگیرید.</p><a routerLink="/contact">تماس با نورستان <span>←</span></a></div></section>
`,styleUrl:'./home.component.css'})
export class HomeComponent { protected readonly products=products; protected readonly categories=categories; }
