import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import { RouterLink } from '@angular/router';
import { ProductSummary } from '../core/catalog-data';

@Component({selector:'app-product-card',imports:[RouterLink],changeDetection:ChangeDetectionStrategy.OnPush,template:`
<a class="card" [routerLink]="['/products',product().slug]">
  <div class="visual" [style.--accent]="product().accent"><span class="luminaire"></span><span class="beam"></span><small>{{product().code}}</small></div>
  <div class="body"><span>{{product().category}}</span><h3>{{product().name}}</h3><p>{{product().description}}</p><b>مشاهده جزئیات <i aria-hidden="true">←</i></b></div>
</a>`,styles:[`:host{display:block}.card{display:block;overflow:hidden;height:100%;border:1px solid var(--color-border);border-radius:var(--radius-lg);background:linear-gradient(145deg,color-mix(in srgb,var(--color-surface) 92%,transparent),rgb(5 9 18/70%));color:var(--color-text);text-decoration:none;box-shadow:var(--shadow-surface);transition:transform var(--duration-base),border-color var(--duration-base),box-shadow var(--duration-base)}.card:hover{transform:translateY(-5px);border-color:color-mix(in srgb,var(--color-primary) 55%,var(--color-border));box-shadow:var(--shadow-surface),0 0 36px var(--color-glow)}.visual{position:relative;display:grid;place-items:center;min-height:19rem;overflow:hidden;background:radial-gradient(circle at 50% 42%,color-mix(in srgb,var(--accent) 26%,transparent),transparent 28%),linear-gradient(135deg,#0b1421,#05080e)}.visual:after{content:'';position:absolute;inset:0;background:linear-gradient(110deg,transparent 25%,rgb(255 255 255/5%) 50%,transparent 75%);transform:translateX(80%);transition:transform .65s}.card:hover .visual:after{transform:translateX(-80%)}.luminaire{position:relative;z-index:2;width:7rem;height:2.3rem;border:1px solid color-mix(in srgb,var(--accent) 60%,white);border-radius:50%;background:linear-gradient(#263746,#080c12);box-shadow:inset 0 -.35rem .7rem var(--accent),0 1rem 3rem color-mix(in srgb,var(--accent) 20%,transparent);transform:perspective(20rem) rotateX(62deg)}.beam{position:absolute;width:12rem;height:12rem;border-radius:50%;background:radial-gradient(circle,color-mix(in srgb,var(--accent) 16%,transparent),transparent 66%)}.visual small{position:absolute;inset-inline-start:1rem;inset-block-end:1rem;color:var(--color-text-muted);font-family:monospace;direction:ltr}.body{padding:1.4rem}.body>span{color:var(--color-primary);font-size:.78rem}.body h3{margin:.25rem 0 .55rem;font-size:1.35rem}.body p{min-height:3.4rem;margin:0;color:var(--color-text-muted);font-size:.87rem;line-height:1.8}.body b{display:inline-block;margin-block-start:1.25rem;color:var(--color-text);font-size:.83rem}.body i{font-style:normal;color:var(--color-primary)}`]})
export class ProductCardComponent { readonly product=input.required<ProductSummary>(); }
